name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git remote add hf https://akshay-20-9-e:$HF_TOKEN@huggingface.co/spaces/akshay-20-9-e/FlowGraphs-engine
          git subtree split --prefix engine -b hf-deploy
          git push hf hf-deploy:main --force
